#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from build_food_assets import load_food_specs, parse_food_list_line
from parse_fooddata_central import (
    DISH_TOKENS,
    CONNECTOR_TOKENS,
    DESCRIPTOR_TOKENS,
    food_category_text,
    iter_food_dicts,
    iter_json_files,
    load_json,
    load_selection_overrides,
    manual_override_matches,
    match_score,
)
from nutrition_utils import normalize_text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Inspect top USDA candidate matches for sports nutrition food queries.")
    parser.add_argument("--input", nargs="+", required=True, help="USDA extracted JSON file(s) or directories.")
    parser.add_argument("--food-list", default="", help="Optional food list TXT/JSON. If provided without --queries, all foods are inspected.")
    parser.add_argument("--queries", nargs="*", default=[], help="Optional explicit food queries to inspect.")
    parser.add_argument("--unmatched-json", default="", help="Optional unmatched food JSON generated by build_food_assets.py.")
    parser.add_argument("--selection-json", default="", help="Optional selection JSON. If provided, only candidates consistent with the manual rule are shown.")
    parser.add_argument("--top-k", type=int, default=10, help="Number of top candidates to keep per query.")
    parser.add_argument("--output-json", default="", help="Optional output JSON path for candidate lists.")
    return parser.parse_args()


def load_queries(args: argparse.Namespace) -> list[dict[str, str]]:
    seen: set[str] = set()
    queries: list[dict[str, str]] = []

    def add_query(food_name: str, zh_name: str = "") -> None:
        raw_name = food_name.strip()
        if not raw_name:
            return
        parsed_name, parsed_zh = parse_food_list_line(raw_name)
        key = parsed_name or raw_name
        zh = zh_name.strip() or parsed_zh
        if not key:
            return
        normalized = key.lower()
        if normalized in seen:
            return
        seen.add(normalized)
        queries.append({"food_name": key, "display_name_zh": zh})

    for item in args.queries:
        add_query(str(item))

    if args.unmatched_json:
        path = Path(args.unmatched_json)
        if not path.exists():
            raise SystemExit(f"Unmatched JSON not found: {path}")
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, list):
            raise SystemExit("Unmatched JSON must be an array.")
        for item in payload:
            if not isinstance(item, dict):
                continue
            add_query(str(item.get("food_name", "")), str(item.get("display_name_zh", "")))

    if args.food_list:
        for spec in load_food_specs(args.food_list):
            add_query(str(spec.get("food_name", "")), str(spec.get("display_name_zh", "")))

    if not queries:
        raise SystemExit("No queries provided. Use --queries, --unmatched-json, or --food-list.")
    return queries


def candidate_record(food: dict[str, Any], source_dataset: str, score: tuple[int, int, int, int, int], mode: str) -> dict[str, Any]:
    return {
        "score": list(score),
        "match_mode": mode,
        "fdc_id": str(food.get("fdcId", "") or food.get("fdc_id", "")).strip() or None,
        "description": str(food.get("description") or food.get("lowercaseDescription") or food.get("foodDescription") or "").strip() or None,
        "food_category": food_category_text(food) or None,
        "data_type": str(food.get("dataType") or food.get("foodClass") or "").strip() or None,
        "source_dataset": source_dataset,
    }


def loose_match_score(food_name: str, query: str, food_category: str) -> tuple[int, int, int, int, int] | None:
    normalized_name = normalize_text(food_name)
    normalized_query = normalize_text(query)
    normalized_category = normalize_text(food_category)
    if not normalized_name or not normalized_query:
        return None

    query_tokens = [token for token in normalized_query.split() if token]
    name_tokens = [token for token in normalized_name.split() if token]
    if not query_tokens or not name_tokens:
        return None

    name_set = set(name_tokens)
    query_set = set(query_tokens)
    overlap = len(query_set & name_set)
    if overlap == 0 and normalized_query not in normalized_name and not any(token in normalized_name for token in query_tokens):
        return None

    descriptor_penalty = sum(1 for token in name_tokens if token in DESCRIPTOR_TOKENS)
    dish_penalty = sum(1 for token in name_tokens if token in DISH_TOKENS)
    connector_penalty = sum(1 for token in name_tokens if token in CONNECTOR_TOKENS)
    missing_tokens = len(query_set - name_set)
    extra_tokens = max(0, len(name_tokens) - overlap)
    category_penalty = 0 if any(token in normalized_category for token in query_tokens) else 1
    substring_penalty = 0 if normalized_query in normalized_name else 1

    return (
        missing_tokens,
        substring_penalty + category_penalty,
        dish_penalty + connector_penalty,
        descriptor_penalty,
        extra_tokens,
    )


def main() -> int:
    args = parse_args()
    queries = load_queries(args)
    selection_overrides = load_selection_overrides(args.selection_json)
    json_files = list(iter_json_files(args.input))
    if not json_files:
        raise SystemExit("No JSON files were found under --input.")

    top_k = max(1, args.top_k)
    strict_candidates_by_query: dict[str, list[dict[str, Any]]] = {item["food_name"]: [] for item in queries}
    loose_candidates_by_query: dict[str, list[dict[str, Any]]] = {item["food_name"]: [] for item in queries}
    zh_name_by_query = {item["food_name"]: item.get("display_name_zh", "") for item in queries}

    def push(bucket: list[dict[str, Any]], entry: dict[str, Any]) -> None:
        bucket.append(entry)
        bucket.sort(key=lambda item: tuple(item["score"]) + (item.get("description") or "",))
        if len(bucket) > top_k:
            del bucket[top_k:]

    for file_index, json_path in enumerate(json_files, start=1):
        print(f"[{file_index}/{len(json_files)}] scanning {json_path}")
        payload = load_json(json_path)
        source_dataset = json_path.parent.name or json_path.stem
        for food in iter_food_dicts(payload):
            raw_name = str(food.get("description") or food.get("lowercaseDescription") or food.get("foodDescription") or "").strip()
            if not raw_name:
                continue
            raw_category = food_category_text(food)
            for query_item in queries:
                query = query_item["food_name"]
                if not manual_override_matches(food, query, selection_overrides):
                    continue
                strict_score = match_score(raw_name, query, raw_category)
                if strict_score is not None:
                    push(strict_candidates_by_query[query], candidate_record(food, source_dataset, strict_score, "strict"))
                    continue
                loose_score = loose_match_score(raw_name, query, raw_category)
                if loose_score is not None:
                    push(loose_candidates_by_query[query], candidate_record(food, source_dataset, loose_score, "loose"))

    output: list[dict[str, Any]] = []
    for query_item in queries:
        query = query_item["food_name"]
        strict_candidates = strict_candidates_by_query.get(query, [])
        loose_candidates = loose_candidates_by_query.get(query, [])
        output.append(
            {
                "food_name": query,
                "display_name_zh": zh_name_by_query.get(query, "") or None,
                "candidates": strict_candidates if strict_candidates else loose_candidates,
                "candidate_mode": "strict" if strict_candidates else ("loose" if loose_candidates else "none"),
            }
        )

    if args.output_json:
        output_path = Path(args.output_json)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Wrote candidate lists to {output_path}")
    else:
        for item in output:
            food_name = item["food_name"]
            zh_name = item.get("display_name_zh") or ""
            suffix = f" | {zh_name}" if zh_name else ""
            print(f"\n=== {food_name}{suffix} ===")
            candidates = item.get("candidates", [])
            if not candidates:
                print("(no candidates)")
                continue
            print(f"mode={item.get('candidate_mode')}")
            for index, cand in enumerate(candidates, start=1):
                print(
                    f"[{index}] mode={cand.get('match_mode')} score={cand['score']} fdc_id={cand.get('fdc_id')} description={cand.get('description')} "
                    f"category={cand.get('food_category')} data_type={cand.get('data_type')}"
                )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
